services:
  flask-app:
    build: 
      context: .
      dockerfile: ./Dockerfile
      args:
        - MONGODB_CONN_STRING=${MONGODB_CONN_STRING}
        - SPELLING_API_KEY=${SPELLING_API_KEY}
    ports:
      - "80:80" 
    
